### ISSUE TITLE
Error while running node .\tests\analysis.js

### ISSUE THREAD

**Issue by hacarra** [Mathieu2301/TradingView-API#2]
npm install ws OK
npm install jszip OK

PS C:\Users\XXXXXX\Source\Repos\TradingView-API> node .\tests\analysis.js
C:\Users\XXXXXX\Source\Repos\TradingView-API\miscRequests.js:312
        value: settings[input.internalID] ?? settings[i] ?? input.defval,
                                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\XXXXXX\Source\Repos\TradingView-API\main.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

**Comment by Mathieu2301** [comment]
Have you changed the content of .\tests\analysis.js file ?
What is your NodeJS version ?

**Comment by marcelbonnet** [comment]
Hi. Same problem here. May you help?

To give you a clue, I wrote the steps for _prices.js_ :

```
node -v
v10.19.0
```

```
mkdir /tmp/tv
cd /tmp/tv
npm i @mathieuc/tradingview
```

Then I created a file _prices.js_ with the same content of your README.

```
node prices.js                                                                                                     
internal/modules/cjs/loader.js:638                                                                                                              
    throw err;                                                                                                                                  
    ^                                                                   
                                                                                                                                                
Error: Cannot find module 'tradingview'
```

So I changed the _require_ in _prices.js_ from _tradingview_ to _@mathieuc/tradingview_ , then I ran it again : 
 
```
node prices.js
/tmp/tv/node_modules/@mathieuc/tradingview/miscRequests.js:312
        value: settings[input.internalID] ?? settings[i] ?? input.defval,
                                           ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/tv/node_modules/@mathieuc/tradingview/main.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by marcelbonnet** [comment]
SOLVED by installing _nvm_ and running node version 17.0.1 : 

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
. ~/.bashrc
nvm install node
```

Thanks for the package. Let's explore it !

**Comment by hacarra** [comment]
> Have you changed the content of .\tests\analysis.js file ? What is your NodeJS version ?

I didn't change the content. My node version is v12.18.2.

**Comment by Mathieu2301** [comment]
It works with node v16 but not with v12.
If you can't update NodeJS, just replace in ``miscRequests.js:312`` file :
```javscript
value: settings[input.internalID] ?? settings[i] ?? input.defval,
```
by
```javscript
value: settings[input.internalID] || settings[i] || input.defval,
```

**Comment by hacarra** [comment]
It worked replacing miscRequests.js:312 as recommended.
